version: '3.2'
services:
    nginx:
        build:
            context: ./
            dockerfile: _docker/nginx.Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8000:80"
        links:
            - php-fpm
        container_name: app_nginx
        depends_on:
            - php-fpm
            - mysql
            - phpmyadmin

    php-fpm:
        build:
            context: ./
            dockerfile: _docker/php-fpm.Dockerfile
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        links:
            - mysql
        container_name: app_php_fpm

    mysql:
        image: mysql:8.0
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "3316:3306"
        container_name: app_mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=secret
            - UPLOAD_LIMIT=64M
        restart: always
        ports:
            - "8081:80"

    composer:
        build:
            context: ./
            dockerfile: _docker/composer.Dockerfile
        volumes:
            - ./:/var/www/
        container_name: app_composer

    artisan:
        build:
            context: ./
            dockerfile: _docker/php-fpm.Dockerfile
        volumes:
            - ./:/var/www
        entrypoint: [ "php", "/var/www/artisan" ]
        container_name: app_artisan
